spring:
  application:
    name: app
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  devtools:
    restart:
      enabled: true
      poll-interval: 1s
      quiet-period: 400ms

server:
  port: 8080
logging:
  level:
    org.hibernate.SQL: DEBUG
    web: DEBUG
